export const TABS_POSITION = {
    FIRST: 0,
    SECOND: 1,
    THIRD: 2,
    FOURTH: 3,
    FIFTH: 4,
    SIXTH: 5,
    SEVENTH: 6,
    EIGHTH: 7,
    NINETH: 8,
};

export const GESTION_USUARIOS = {
    title: 'Gestión de usuarios',
    titleTab1: 'ACTIVOS',
    titleTab2: 'DESHABILITADOS',
    titleTab3: 'CAMBIO DE CONTRASEÑA',
    accion1: 'VER',
    accion2: 'CAMBIAR',
    menuItem1: 'Editar',
    menuItem2: 'Deshabilitar',
    menuItem3: 'Eliminar',
    menuItem4: 'Activar',
    creacion: 'Creación de usuarios',
    edicion: 'Edición de usuarios',
    completar: 'Complete o verifique la información.',
    general: 'Datos generales',
    especificos: 'Datos específicos',
    aprobaciones: 'Aprobaciones y autorizaciones',
    actuales: 'Datos actuales',
    otras: 'Otras solicitudes',
    parametros: 'Parámetros'
}

export const GESTION_ORDENES = {
    vales: 'Registro de expedientes',
    ordenes: 'Gestión de órdenes de pago',
    titleTab1: 'Creados',
    titleTab2: 'Pendientes de aprobación',
    titleTab3: 'Aprobados',
    titleTab4: 'Pendientes de desembolso',
    titleTab5: 'Pendientes de liquidar',
    titleTab6: 'Finalizados',
    titleTab7: 'Pendientes por aprobar',
    titleTab8: 'Pendientes por autorizar',
    titleTab9: 'Rechazados',
    accion1: 'VER',
    actuales: 'Datos actuales',
    otras: 'Otras solicitudes',
    creacion: 'Creación de expedientes',
    edicion: 'Edición de expedientes',
    completar: 'Complete o verifique la información.',
    general: 'Datos generales',
    menuItem1: 'Enviar',
    menuItem2: 'Editar',
    menuItem3: 'Eliminar',
    menuItem4: "Aprobar",
    menuItem5: "Autorizar",
    menuItem6: "Rechazar",
    menuItem7: "Desembolsar",
    menuItem8: "Liquidar",
    menuItem9: "Finalizar",
    motivo_rechazo: 'Motivo del rechazo',
    historico_control: 'Histórico y control de vales'
}

export const GESTION_RECIBOS = {
    vales: 'Gestión de recibos',
    titleTab1: 'borrador',
    titleTab2: 'Pendientes de aprobación',
    titleTab3: 'Pendientes de autorización',
    titleTab4: 'Pendientes de desembolso',
    titleTab5: 'Pendientes de liquidar',
    titleTab6: 'Finalizados',
    titleTab7: 'Pendientes por aprobar',
    titleTab8: 'Pendientes por autorizar',
    titleTab9: 'Rechazados',
    accion1: 'VER',
    actuales: 'Datos actuales',
    otras: 'Otras solicitudes',
    creacion: 'Creación de recibos',
    edicion: 'Edición de recibos',
    completar: 'Complete o verifique la información.',
    general: 'Datos generales',
    menuItem1: 'Enviar',
    menuItem2: 'Editar',
    menuItem3: 'Eliminar',
    menuItem4: "Aprobar",
    menuItem5: "Autorizar",
    menuItem6: "Rechazar",
    menuItem7: "Desembolsar",
    menuItem8: "Liquidar",
    menuItem9: "Finalizar",
    motivo_rechazo: 'Motivo del rechazo',
    historico_control: 'Histórico y control de recibos',
    reintegro: 'Reintegro del 50% del gasto total',
    detalles_generales: 'Detalles generales'
}

export const GESTION_PARAMETROS = {
    title: 'Gestión de parámetros',
    titleTab1: 'ACTIVOS',
    titleTab2: 'FINALIZADOS',
    titleTab3: 'CAMBIO DE CONTRASEÑA',
    accion1: 'VER',
    accion2: 'CAMBIAR',
    menuItem1: 'Editar',
    menuItem2: 'Deshabilitar',
    menuItem3: 'Eliminar',
    menuItem4: 'Activar',
    creacion: 'Creación de parámetros',
    edicion: 'Edición de usuarios',
    completar: 'Complete o verifique la información.',
    general: 'Datos generales',
    especificos: 'Datos específicos',
    aprobaciones: 'Aprobaciones y autorizaciones',
    actuales: 'Datos actuales',
    otras: 'Otras solicitudes'
}

export const GESTION_ROLES = {
    title: 'Gestión de roles',
    titleTab1: 'borrador',
    titleTab2: 'Pendientes de aprobación',
    titleTab3: 'Pendientes de autorización',
    titleTab4: 'Pendientes de desembolso',
    titleTab5: 'Pendientes de liquidar',
    titleTab6: 'Finalizados',
    titleTab7: 'Pendientes por aprobar',
    titleTab8: 'Pendientes por autorizar',
    titleTab9: 'Rechazados',
    accion1: 'VER',
    actuales: 'Datos actuales',
    otras: 'Otras solicitudes',
    creacion: 'Creación de roles',
    edicion: 'Edición de roles',
    completar: 'Complete o verifique la información.',
    general: 'Datos generales',
    menuItem1: 'Enviar',
    menuItem2: 'Editar',
    menuItem3: 'Eliminar',
    menuItem4: "Aprobar",
    menuItem5: "Autorizar",
    menuItem6: "Rechazar",
    menuItem7: "Desembolsar",
    menuItem8: "Liquidar",
    menuItem9: "Finalizar",
    motivo_rechazo: 'Motivo del rechazo',
    historico_control: 'Histórico y control de vales'
}

export const GESTION_FISCALIAS = {
    title: 'Gestión de fiscalías',
    titleTab1: 'borrador',
    titleTab2: 'Pendientes de aprobación',
    titleTab3: 'Pendientes de autorización',
    titleTab4: 'Pendientes de desembolso',
    titleTab5: 'Pendientes de liquidar',
    titleTab6: 'Finalizados',
    titleTab7: 'Pendientes por aprobar',
    titleTab8: 'Pendientes por autorizar',
    titleTab9: 'Rechazados',
    accion1: 'VER',
    actuales: 'Datos actuales',
    otras: 'Otras solicitudes',
    creacion: 'Creación de fiscalías',
    edicion: 'Edición de fiscalías',
    completar: 'Complete o verifique la información.',
    general: 'Datos generales',
    menuItem1: 'Enviar',
    menuItem2: 'Editar',
    menuItem3: 'Eliminar',
    menuItem4: "Aprobar",
    menuItem5: "Autorizar",
    menuItem6: "Rechazar",
    menuItem7: "Desembolsar",
    menuItem8: "Liquidar",
    menuItem9: "Finalizar",
    motivo_rechazo: 'Motivo del rechazo',
    historico_control: 'Histórico y control de vales'
}

export const GESTION_PUESTOS = {
    title: 'Gestión de puestos',
    titleTab1: 'borrador',
    titleTab2: 'Pendientes de aprobación',
    titleTab3: 'Pendientes de autorización',
    titleTab4: 'Pendientes de desembolso',
    titleTab5: 'Pendientes de liquidar',
    titleTab6: 'Finalizados',
    titleTab7: 'Pendientes por aprobar',
    titleTab8: 'Pendientes por autorizar',
    titleTab9: 'Rechazados',
    accion1: 'VER',
    actuales: 'Datos actuales',
    otras: 'Otras solicitudes',
    creacion: 'Creación de puestos',
    edicion: 'Edición de puestos',
    completar: 'Complete o verifique la información.',
    general: 'Datos generales',
    menuItem1: 'Enviar',
    menuItem2: 'Editar',
    menuItem3: 'Eliminar',
    menuItem4: "Aprobar",
    menuItem5: "Autorizar",
    menuItem6: "Rechazar",
    menuItem7: "Desembolsar",
    menuItem8: "Liquidar",
    menuItem9: "Finalizar",
    motivo_rechazo: 'Motivo del rechazo',
    historico_control: 'Histórico y control de vales'
}

export const GESTION_PERMISOS = {
    title: 'Gestión de permisos',
    titleTab1: 'borrador',
    titleTab2: 'Pendientes de aprobación',
    titleTab3: 'Pendientes de autorización',
    titleTab4: 'Pendientes de desembolso',
    titleTab5: 'Pendientes de liquidar',
    titleTab6: 'Finalizados',
    titleTab7: 'Pendientes por aprobar',
    titleTab8: 'Pendientes por autorizar',
    titleTab9: 'Rechazados',
    accion1: 'VER',
    actuales: 'Datos actuales',
    otras: 'Otras solicitudes',
    creacion: 'Creación de roles',
    edicion: 'Edición de roles',
    completar: 'Complete o verifique la información.',
    general: 'Datos generales',
    menuItem1: 'Enviar',
    menuItem2: 'Editar',
    menuItem3: 'Eliminar',
    menuItem4: "Aprobar",
    menuItem5: "Autorizar",
    menuItem6: "Rechazar",
    menuItem7: "Desembolsar",
    menuItem8: "Liquidar",
    menuItem9: "Finalizar",
    motivo_rechazo: 'Motivo del rechazo',
    historico_control: 'Histórico y control de vales'
}

export const GESTION_REPORTES = {
    title: 'Gestión de permisos',
    accion1: 'VER',
    actuales: 'Datos actuales',
    otras: 'Otras solicitudes',
    reportePlanillaRecibos: 'Reporte de planilla de viáticos no comprobables por medio de recibos',
    reporteRecibosUsuario: 'Reporte de recibos realizados por un usuario específico',
    reporteRecibosAgencia: 'Reporte de recibos realizados por una agencia en específico',
    reporteValesUsuario: 'Reporte de vales realizados por un usuario específico',
    reporteValesAgencia: 'Reporte de vales realizados por una agencia en específico',
    edicion: 'Edición de roles',
    completar: 'Complete la información necesaria.',
    general: 'Parámetros generales',
    especifico: 'Parámetros específicos',
    motivo_rechazo: 'Motivo del rechazo',
    historico_control: 'Histórico y control de vales'

}